### ISSUE TITLE
Lock and Witness

### ISSUE THREAD

**Issue by zguoguo** [nomic-io/bitcoin-peg#1]
Hi, I saw that in the documentation for PEGGY(https://github.com/cosmos/peggy/tree/master/spec##smart-contract-component), the readme also mentioned that Bitcoin can be linked to cosmos network through a peg zone. However, Bitcoin does not support Smart Contracts, which, I think, play a big role in the witness and lock/unlock step. How do you make Bitcoin perform thoses steps without using smart contract?

**Comment by mappum** [comment]
Replying very late here, but I just want to point out that Bitcoin does in fact support smart contracts. The details for the script are now written up in the design document: https://github.com/mappum/bitcoin-peg/blob/master/bitcoinPeg.md
